global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "django"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"]
